---
cold_storage_folder: "/s/fran_storage" # used to hold data for inference,checkpoints, original raw data should also be here.
rapid_access_folder: "/home/ub/datasets/preprocessed"    # this data is used during each Deeplearning run. Ideally an SSD
projects_folder: "/s/fran_storage/projects"
neptune_workspace_name: "johndoe"
neptune_api_token: "abcd0128"
